### ISSUE TITLE
Parent component's onClick occurs twice when Checkbox, Switch component is used as Controlled

### ISSUE THREAD

**Issue by junghyeonsu** [chakra-ui/zag#633]
# 🐛 Bug report

_Before we go any further, I kept thinking if there was a way to fix it, and I played around with the machine, but there wasn't, so I raised an issue.
Please let me know if this is the intended behavior or if I'm misunderstanding something._

When using a `<Checkbox />`, `<Switch />` component in Controlled mode and placing the onClick in a container that encloses the component, the onClick is executed twice.

In my project, I don't use chakra, only checkbox and switch machines, and the same thing happens, so I thought it was a problem on the zag side.

## 💥 Steps to reproduce

1. Use Checkbox, Switch components in controlled mode. (only use `isChecked` prop)
2. Wrap that Checkbox or Switch component in a container.
3. Add a toggle onClick event to that container.
4. And if you **click on the container**, and if you **click on the overlap between the container and the checkbox or switch**, you can see the difference.

## 💻 Link to reproduction

- Stackblitz reproduction (editor) : https://stackblitz.com/edit/react-ts-af4b8w?file=App.tsx
- Stackblitz reproduction (app) : https://react-ts-af4b8w.stackblitz.io

In the link, I reproduced it using `Chakra-ui`, but it's the same using `zag-js/checkbox@0.7.0` and `zag-js/switch@0.7.0`, and it's the same using `ark-ui/react@0.3.0` with those versions.

Replaced `zag-js/core` with `Chakra-ui` because it was behaving badly in stackblitz. Locally, you can try the same with the code below.

<img width="515" alt="스크린샷 2023-05-12 오후 2 42 43" src="https://github.com/chakra-ui/zag/assets/54893898/92817eb0-4554-4a0a-97e3-6bf23fe4298f">

<details>
<summary>open/close</summary>

```tsx
// App.tsx
import './App.css'

import * as React from 'react'
import { useToast } from '@chakra-ui/react'
import {
  Checkbox,
  CheckboxControl,
  CheckboxInput,
  CheckboxLabel,
  Switch,
  SwitchControl,
  SwitchLabel,
  SwitchInput,
  SwitchThumb,
} from '@ark-ui/react'

function App() {
  const [isChecked, setIsChecked] = React.useState(false)
  const toast = useToast();

  const toggleChecked = (event: React.MouseEvent<HTMLDivElement>) => {
    console.log("event target is", event.target);

    setIsChecked((prev) => !prev);
    toast({
      title: "Toggled!",
      duration: 2000,
    })
  }

  return (
    <div id="app">
      <div id="container" onClick={toggleChecked}>
        <p id="description">Zag, Ark Checkbox</p>
        <Checkbox checked={isChecked} readOnly>
          <CheckboxLabel>{isChecked ? "checked" : "unchecked"}</CheckboxLabel>
          <CheckboxInput />
          <CheckboxControl
            style={{
              width: "10px",
              height: "10px",
              border: "1px solid black",
              backgroundColor: isChecked ? "black" : "white",
            }}
          />
        </Checkbox>
      </div>

      <div id="container" onClick={toggleChecked}>
        <p id="description">Zag, Ark Switch</p>
        <Switch checked={isChecked} readOnly>
          <SwitchLabel>{isChecked ? "checked" : "unchecked"}</SwitchLabel>
          <SwitchInput />
          <SwitchThumb />
          <SwitchControl
            style={{
              width: "10px",
              height: "10px",
              border: "1px solid black",
              backgroundColor: isChecked ? "black" : "white",
            }}
          />
        </Switch>
      </div>

      <div id="container" onClick={toggleChecked}>
        <p id="description">HTML Native Input</p>
        <input checked={isChecked} type="checkbox" readOnly />
        {isChecked ? "checked" : "unchecked"}
      </div>
    </div>
  )
}

export default App
```

```css
/* App.css */
#root {
  width: 100vw;
  height: 100vh;

  display: flex;
  flex-wrap: wrap;
  justify-content: center;
  align-items: center;
}

#app {
  width: 100%;
  height: 100%;

  display: flex;
  flex-wrap: wrap;
  justify-content: center;
  align-items: center;

  gap: 20px;
}

#container {
  width: 300px;
  height: 300px;

  display: flex;
  position: relative;
  flex-direction: column;
  flex-wrap: wrap;
  justify-content: center;
  align-items: center;

  background-color: aliceblue;
}

#description {
  position: absolute;
  top: 0;
  left: 0;
  margin: 20px;
  
  font-size: 14px;

  color: rgb(25, 25, 25);
}

#container:hover {
  cursor: pointer;
}
```

</details>

## 🧐 Expected behavior

- onClick event fire only once when click **click on the overlap between the container and the checkbox or switch**
- You can see HTML native input component fired onClick event once at below

![onclick-twice](https://github.com/chakra-ui/zag/assets/54893898/c992786b-6972-4c00-92f9-7dd645e4950e)

## 🧭 Possible Solution

<img width="961" alt="스크린샷 2023-05-12 오후 2 14 38" src="https://github.com/chakra-ui/zag/assets/54893898/24820918-fdce-431f-a076-391b2900ec6b">

I did some debugging and realized that the event.target in the parent onClick event comes from **two parts**.

One is the part of the component that is clicked, and one is the **input anatomy**.

## 🌍 System information

| Software         | Version(s) |
| ---------------- | ---------- |
| Zag Version      |  `@zag-js/checkbox@0.7.0`, `@zag-js/switch@0.7.0`, `@ark-ui/react@0.3.0`, `@chakra-ui/react@2.6.1`     |
| Browser          |     Chrome 112.0.5615.137 (arm64)       |
| Operating System |      Apple M1 Max Mac OS 12.6.1 Monterey      |
